sudo: required
os: linux
dist: xenial
service:
- docker
env:
  global:
  - MY_NAME=travis-ci
  - MY_TARGET_DIST=sagemath/sagemath
  - MY_MODE="sagemath"
  - MY_TARGET_MOUNT=/tell/security-analysis-plos-one-2016
before_install:
- env | sort
- sudo apt update
- sudo apt install -y wget > /dev/null
- docker pull $MY_TARGET_DIST
- docker run --name $MY_NAME -v $TRAVIS_BUILD_DIR:$MY_TARGET_MOUNT -td $MY_TARGET_DIST /bin/bash
- docker exec -ti $MY_NAME bash -c "sudo apt update" > /dev/null
install:
- wget -O S1_File.txt https://ndownloader.figshare.com/files/14402309
- wget -O S2_File.txt https://ndownloader.figshare.com/files/14402312
- wget -O S3_File.sage https://ndownloader.figshare.com/files/14402315
- pwd
- ls -la
- docker exec -ti $MY_NAME bash -c "sudo apt install -y make" > /dev/null
script:
- docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT; sudo sage S3_File.sage"
notifications:
  on_success: change
  on_failure: always
# vim: set expandtab shiftwidth=2 softtabstop=2 :
